# Generated by Django 3.2.13 on 2022-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField(verbose_name='Texto Principal')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Data Publicação')),
            ],
        ),
    ]
